# Generated by Django 5.2.7 on 2025-11-05 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCultivo', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('typeCultivo', models.CharField(choices=[('hortaliza', 'Hortaliza'), ('frutales', 'Frutales'), ('cereales', 'Cereales'), ('leguminosas', 'Leguminosas'), ('tuberculos', 'Tuberculos')])),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
